base:
  DOIAU: "NO"
  DO_JEDIATMVAR: "NO"
  DO_JEDIATMENS: "NO"
  DO_JEDIOCNVAR: "NO"
  DO_JEDISNOWDA: "NO"
  DO_MERGENSST: "NO"
  DO_STARTMEM_FROM_JEDIICE: "NO"
  DO_GOES: "NO"
  DO_BUFRSND: "NO"
  DO_GEMPAK: "NO"
  DO_AWIPS: "NO"
  DO_NPOESS: "NO"
  DO_TRACKER: "NO"
  DO_GENESIS: "NO"
  DO_GENESIS_FSU: "NO"
  DO_METP: "YES"
  FHMAX_GFS: 120
  FHOUT_GFS: 3
  FHOUT_AERO: 3
  FHMAX_HF_GFS: 0
  FCST_BREAKPOINTS: ""
  DO_TEST_MODE: "NO"
  DO_AERO_FCST: "YES"
  DO_AERO_INIT: "YES"
  APP: "ATMA"
  DO_AERO: "YES"
  DO_ATM: "YES"
  USE_OCN_ENS_PERTURB_FILES: "NO"
  USE_ATM_ENS_PERTURB_FILES: "NO"

aerosol_init:
  AERO_CONFIG_DIR: "{FIXgfs}/ufs/gocart"

# config.aero has just a system-specific path to add.
# This is handled by the setup_expt.py, but it has to be told to write to it.
aero: {}
